### ISSUE TITLE
Copyright infringement G6EJD weather station

### ISSUE THREAD

**Issue by G6EJD** [Xinyuan-LilyGO/LilyGo-EPD47#1]
I will give you 5-days to remove the weather station code or I will file a GitHub takedown action.

You have taken my code and listed as yours. 

This is the second time you have done this, the first time the listing was removed by GitHub.

**Comment by lewisxhe** [comment]
Sorry, it has been deleted, I have explained the source of the driver and examples in the README, and we have emailed to you.
