### ISSUE TITLE
compile error with demo sketch

### ISSUE THREAD

**Issue by HDMatGIT** [Xinyuan-LilyGO/LilyGo-EPD47#101]
With the demo sketch I get this compilation error: 
C:\Users\hdm\AppData\Local\Temp\.arduinoIDE-unsaved2023726-3632-1dsa4p0.isof\demo\demo.ino:15:10: fatal error: pcf8563.h: No such file or directory
 #include "pcf8563.h"
          ^~~~~~~~~~~
compilation terminated.
Mehrere Bibliotheken wurden für "SD.h" gefunden
  Benutzt: C:\Users\hdm\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\SD
  Nicht benutzt: C:\Users\hdm\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: pcf8563.h: No such file or directory

I tried to install according libraries but none of them worked and produced further errors.
Can somebody point me to what is missing or the correct library?
Thanks

**Comment by G6EJD** [comment]
You need to install the 8653 library there are plenty available.

**Comment by HDMatGIT** [comment]
Thank you. I did that and tried some different ones. In none of them Line 42 of the demo sketch (PCF8563_Class rtc;) did work...,

**Comment by G6EJD** [comment]
https://github.com/Bill2462/PCF8563-Arduino-Library

**Comment by G6EJD** [comment]
Lily go should really have included links to all the libraries they use.

**Comment by HDMatGIT** [comment]
Thank you again! I tried this library already yesterday, but then I get the error:
Compilation error: 'PCF8563_Class' does not name a type; did you mean 'PCF8563_H'?
I then tried PCF8563_H rtc; and then I get this error:
Compilation error: 'rtc' does not name a type

**Comment by HDMatGIT** [comment]
I also tried "PCF8563 rtc;" This produces a new error:
Compilation error: 'class PCF8563' has no member named 'begin'

**Comment by G6EJD** [comment]
Try the Adafruit rtclib

**Comment by HDMatGIT** [comment]
That did not change anything.

**Comment by lbuque** [comment]
https://github.com/lewisxhe/PCF8563_Library.git
The url of the library is written in platformio.ini.

**Comment by HDMatGIT** [comment]
Thank you Ibuque that did the trick!

**Comment by HDMatGIT** [comment]
Great and quick help, thank you!
