### ISSUE TITLE
Touch screen on AliExpress no longer available ?

### ISSUE THREAD

**Issue by markbirss** [Xinyuan-LilyGO/LilyGo-EPD47#11]
The page no longer available for the Touch Screen ?

https://www.aliexpress.com/item/1005001835564831.html?spm=a2g0s.12269583.0.0.5950236fhJRePx

**Comment by lewisxhe** [comment]
It's here

https://www.aliexpress.com/item/1005002006389042.html?spm=2114.12010612.8148356.15.39a05456Ynz8bp

**Comment by markbirss** [comment]
Ok

**Comment by milosvvv** [comment]
any plans on having it on banggood? I cannot use aliexpress

**Comment by jtherin** [comment]
What about the sharp one for duan-qie.stl ?
