### ISSUE TITLE
Unable to upload to ESP32 S3. Wrong --chip argument?

### ISSUE THREAD

**Issue by burk** [Xinyuan-LilyGO/LilyGo-EPD47#111]
Getting this error when trying to upload the demo example to a `T5-4.7 S3`
```
A fatal error occurred: This chip is ESP32-S3 not ESP32. Wrong --chip argument?
Failed chip erase: uploading error: exit status 2
```
I've installed the latest Arduino IDE, re-installed the latest esp32 boards, and selected the ESP32 dev module. I also tried the ESP32S3 dev module, but then I got the error
```
Compilation error: pcf8563.h: No such file or directory
```
Any ideas?

**Comment by G6EJD** [comment]
You need to install/include the PCF8563 library!

**Comment by burk** [comment]
Oh... I was just following the `Quick instructions` in the README, but failed to see the link to this documentation: https://t5-47-t5-47-plus.readthedocs.io/en/latest/get-started/index.html#install-dependent-libraries.. which links to the required library: https://github.com/lewisxhe/PCF8563_Library.

**Comment by G6EJD** [comment]
Adafruit fork of rtclib will solve it
