### ISSUE TITLE
No valid dependencies solution found: dependency 'Wire' is not available

### ISSUE THREAD

**Issue by Jonansch** [Xinyuan-LilyGO/LilyGo-EPD47#115]
I want to install the library LilyGo EPD47 into my arduino ide 2.3.2 for my lilygo t5 4.7" screen but the following error occured.

Failed to install library: 'LilyGo-EPD47:1.0.0'. No valid dependencies solution found: dependency 'Wire' is not available

can someone help me in this case?

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/assets/22990954/97f94700-7635-423c-9e1b-5cd689b7b560)
already fixed
