### ISSUE TITLE
usb-c pull down on B5 missing

### ISSUE THREAD

**Issue by fleinze** [Xinyuan-LilyGO/LilyGo-EPD47#116]
Accoring to the usb-c standard there needs to be a pulldown resistor of 5.1 kOhm on both CC1 (A5) and CC2 (B5). The board only has one pulldown resistor on CC1. This creates an issue with some usb-c poweradapters where the board is only powered in one of two possible plug orientations.
I know this is not an easy fix but it should be fixed in future revisions an future products.

**Comment by lewisxhe** [comment]
This problem has been corrected in later S3 versions
