### ISSUE TITLE
Touch not working?

### ISSUE THREAD

**Issue by heyudude** [Xinyuan-LilyGO/LilyGo-EPD47#134]
Hi,

I bought this version T5 e-Paper [DE] Touch Non-Soldered Female pin [H716] in the German warehouse.
I get a reboot with touch enabled and without it displays ok.

I used this excellent example code, it uses the default touch.h
https://github.com/tommesaros/EPD-UI-Lib

Anything I missed?

Thanks for your support

**Comment by lewisxhe** [comment]
What kind of touch panel are you using? There are three types, and I can't tell which driver model you are using.

**Comment by heyudude** [comment]
Not sure how to check the type. It is the stock one delivered by the lilygo official store: German office one week ago. No Lilygo logo.

Is there a default program in your repositories to check the type and function? I presume also it is a driver issue.

**Comment by lewisxhe** [comment]
If you just received it, you should be using the latest touch driver, try this example
https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/esp32s3/examples/touch/touch.ino

**Comment by heyudude** [comment]
It works with the demo.
So nothing wrong with the touch screen.

However where to find the new drivers:
#include <TouchDrvGT911.hpp>        
#include <SensorPCF8563.hpp>

maybe something is wrong in the PlatformIO.ini

Thanks for the hint

**Comment by lewisxhe** [comment]
The library is defined here
https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/575e9539868ec6d69f13b1abe5ca4195f415a55d/platformio.ini#L52

**Comment by heyudude** [comment]
Thanks! good to go!

**Comment by heyudude** [comment]
thanks good to go and code!
