### ISSUE TITLE
Version 2.3 Stopped Working / bricked

### ISSUE THREAD

**Issue by NorthernMan54** [Xinyuan-LilyGO/LilyGo-EPD47#137]
I have been working with version 2.3 of this board for a few months now, and had it running for few weeks - https://github.com/NorthernMan54/esp32_balboa_spa

Then a few days ago it just stopped.  And the display is frozen at 5:11 am, and the board no longer responds.  I went and connected it to the laptop I used for development, and no serial port available.  The green and blue led does turn on, but not serial port.  I also tried the Boot/Rst step and no luck.  Also when looking via lsusb, I don't see anything.

Any clues around how to unbrick, or is it dead?

**Comment by lewisxhe** [comment]
If you hold down the BOOT button and insert the USB and still can't find the port, it means it's dead.

**Comment by NorthernMan54** [comment]
Tks

**Comment by pbenaim** [comment]
See here : https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/98

**Comment by NorthernMan54** [comment]
Tks I may give that a try, since I shelved this project I switched to the cyd lvgl based displays available.
