### ISSUE TITLE
Display doesn't refresh

### ISSUE THREAD

**Issue by matrol-min** [Xinyuan-LilyGO/LilyGo-EPD47#138]
Hello,
I used an EPD47 as a dashboard with ESP Home and Homeassistant.
I have been powering this board using a USB cable. Occasionally, when I unplug and reconnect the cable, the display doesn’t refresh and freezes. However, resetting and re-uploading the example code would usually make it work properly again.

Recently, though, after the display froze, no method I tried has been able to refresh it. When I upload example codes from ArduinoIDE, the serial monitor shows logs normally, but the display remains frozen and unchanged.

The examples I uploaded are <drawimages> and <screen repair>. For both examples, the display doesn't refresh and is stuck on the last screen when I disconnect the power.

For reference, the last time it worked correctly, the three buttons on the board were pressed multiple times simultaneously due to interference between the case and the board. Could this be related to the issue?

**Comment by lewisxhe** [comment]
If the serial output is normal but the screen is still frozen, the screen may be damaged. Take a test video and contact the dealer for after-sales service.
