### ISSUE TITLE
Quick start guide not complete

### ISSUE THREAD

**Issue by idanov** [Xinyuan-LilyGO/LilyGo-EPD47#20]
Hello :wave:  I have followed the quick start guide, but when I try to upload the demo example, I get EPS IDF errors:

```
/home/user/snap/arduino/current/Arduino/libraries/LilyGo-EPD47-master/src/i2s_data_bus.c:5:29: fatal error: esp_idf_version.h: No such file or directory
 #include <esp_idf_version.h>
                             ^
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.
```

I am using Ubuntu 20.04 and installed the Arduino IDE snap (tried with a non-snap installation and the result is the same). Should I install ESP-IDF too and how to get the demo to work with Arduino IDE?

**Comment by mol21** [comment]
Hi, I had the same problem on MacOS 11.1 and platformio with VSCode.
I just deleted or commented out the #include <esp_idf_version.h> lines in the code (it is in multiple files) and it compiles and works.

**Comment by Nyessss** [comment]
Hi, I try this too and it worked.
Just delete lines associated with esp_idf_version.h (and if loops) in
/src/i2s_data_bus.c & /src/rmt_pulse.c.

**Comment by idanov** [comment]
I found a workaround by installing the dev version of https://github.com/espressif/arduino-esp32. Nevertheless, the step for installing it is missing from the guide and it's probably worth adding it.

**Comment by lewisxhe** [comment]
Due to the merged request, using the old version of esp32 core will cause compilation errors
