### ISSUE TITLE
Molex Connector - source?

### ISSUE THREAD

**Issue by G6EJD** [Xinyuan-LilyGO/LilyGo-EPD47#22]
Hi not a code issue, but has anyone found a source for the '4pin 2.0 molex 4 p 53015-0410' connectors, nothing found on AliExpress or Digikey.

There are 3 on-board connectors and I'm trying to make a I2C device connection (the LILYGO bme280 board), I want to post some code to show how to read I2C devices.

**Comment by lewisxhe** [comment]
You might be looking for this

https://pt.aliexpress.com/item/4000473537275.html?spm=a2g03.12010612.8148356.31.53e37765faiBCP

**Comment by G6EJD** [comment]
Thank you, exactly what I need.
