### ISSUE TITLE
Where can I find the Weather Example?

### ISSUE THREAD

**Issue by sthufnagl** [Xinyuan-LilyGO/LilyGo-EPD47#24]
Hello,

a lot of screen dumps show a weather example. May I ask "Where can I find this example?"
I know that  epdiy has a weather example, but this dedicated to a different (kindle?) 9.7 " display.
Thanks in advance

BTW, great device with a lot of potential!
:-)

**Comment by G6EJD** [comment]
Contact me via g6ejd.dynu.com or dsbird.org.uk and I’ll send you copy, I have just finished a conversion to this display, finished testing yesterday.

**Comment by sthufnagl** [comment]
Great work! It works out of the box and look very, very good.
Thx

**Comment by G6EJD** [comment]
Good to hear, I think this can be closed now.

**Comment by sthufnagl** [comment]
Works...Thx

**Comment by Jozer99** [comment]
Any chance I could get a copy?  Are you going to be  releasing a version for this dev board on your git page to go along with the versions for other devices?

**Comment by G6EJD** [comment]
Yes, please send me an email via the link above, I’m still improving and testing the sleep function and working on 4-but icons, the version I have now will appear here and my GitHub soon.

**Comment by mengszym** [comment]
Hello, after uploading the water program to epd47 after refreshing the screen, the gray background remains.  how to fix it ?  Thank you in advance for your help and best regards
