### ISSUE TITLE
Waveform File

### ISSUE THREAD

**Issue by vroland** [Xinyuan-LilyGO/LilyGo-EPD47#32]
Hi, 
Recently, I added support for vendor wavforms to epdiy. These are special files that describe how the display must be driven for accurate grayscale.
This allows to make arbitrary grayscale-to-grayscale transitions, which is not possible with the version of epdiy this library is based on at the moment. There are some other improments as well, especially to the user-facing API. So incorporating them or finding a way to keep this fork more up to date should be discussed in a separate issue.
You have sent me the fitting waveform file via e-Mail already, but it would be nice to have it publicly available for anyone who needs it. That would allow me to add the appropriate header to epdiy directly, which would make it way easier for people to get use out of this file.
So: Could you add the V220_C244_BA5701_ED047TC2U1_TC.wbf waveform file to the repository?

Regards,
Valentin

**Comment by markbirss** [comment]
Please upload the **V220_C244_BA5701_ED047TC2U1_TC.wbf** waveform file for all of us

**Comment by LilyGO** [comment]
@vroland Ok.
Sorry, I haven’t logged into GitHub recently
Thank you for your efforts, I should reply to you as soon as possible

**Comment by LilyGO** [comment]
@vroland Have you submitted your pull request? So that I can approve your merge request.
Contributors will also show your name

**Comment by vroland** [comment]
Making a pull request for the waveform implementation only is unfortunately not trivial, because a lot of refactoring happened in epdiy since then. Maybe we should discuss this in https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/33 instead?
Also, publishing the waveform file would be a prerequisite for generating a suitable waveform header.

**Comment by hacksics** [comment]
I've started using epdiy instead of this fork and it makes sense to use the base repository as it has lot of new features and updated frequently. 

But what I have noticed was the image colors are not accurate as EPD47 when using native epdiy. Is this due to using the EPD_BUILTIN_WAVEFORM file instead of vendor waveform? 

@vroland as suggested by @LilyGO  can you create a pull request by just adding the raw waveform file so we can use it to generate header file using waveform_hdrgen.py ?

**Comment by vroland** [comment]
@hacksics Because I'm unsure of the copyright situation, I would prefer that @LilyGO publish the file, since I got it from them.

**Comment by hacksics** [comment]
Ok makes sense. @LilyGO @lewisxhe  can you please chime in..

**Comment by Jason2866** [comment]
+1 @LilyGO for uploading **V220_C244_BA5701_ED047TC2U1_TC.wbf**

**Comment by Jason2866** [comment]
Thx!

**Comment by hacksics** [comment]
@vroland can you please integrate this in to epdiy repo ?

**Comment by entozoon** [comment]
@hacksics [PR created](https://github.com/vroland/epdiy/pull/129)
