### ISSUE TITLE
White text on black background

### ISSUE THREAD

**Issue by hacksics** [Xinyuan-LilyGO/LilyGo-EPD47#48]
Anyone know how I can get the white color text on black background? All I want to do is that fillRect with Black and then write text with white color. 

There are members called

uint8_t fg_color
uint8_t bg_color

But I don't know how should I use it.

**Comment by LilyGO** [comment]
Hello, have you solved your issue?

**Comment by LilyGO** [comment]
Thank you for your feedback. I'm going to close this issue.
