### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by otosan-maker** [Xinyuan-LilyGO/LilyGo-EPD47#49]
Hello, I have tried the test program to use the buttons, IO34 and IO39 works, but IO35 is not.
Is there any special thing with IO35??
I think the other button has problems ... IO0, isn´t it?

**Comment by martinberlin** [comment]
I tried all buttons using this repository and they work great for me
https://github.com/atomic14/diy-esp32-epub-reader
Maybe share some code of how you are reading them because all button GPIOs are working alright for me when trying that ePub reader.
