### ISSUE TITLE
Using other displays

### ISSUE THREAD

**Issue by giladaya** [Xinyuan-LilyGO/LilyGo-EPD47#65]
Is there a way to make this board work with a 6" display (for example an ED060XC3)?
I know it can work with a specific 5.2" screen (ED052TC2), but it's still not large enough for my needs.

Thanks

**Comment by LilyGO** [comment]
The socket on the board seems to be incompatible with ED060XC3, epdiy is adapted, you can refer to this link https://github.com/vroland/epdiy.git

**Comment by giladaya** [comment]
Yeah, I know about epdiy, but producing an actual board is not trivial so I was hoping there's a way to use lilygo-epd47 somehow (maybe using a simple cable adapter).
Sorry, I still have a lot to learn about driving EPD's

**Comment by upisqueen-blip** [comment]
I've reviewed your open-source repo, but it seems everything is tailored for the 50-pin ED052TC4. I'm currently working with the 40-pin ED052TC2 (also on an ESP32-S3). Would it be possible for you to share any reference schematics or code examples to get this specific screen running? It would save me a lot of trial and error. Thanks in advance!
