### ISSUE TITLE
请求 驱动方面的帮助

### ISSUE THREAD

**Issue by PickaxeHit** [Xinyuan-LilyGO/LilyGo-EPD47#67]
你好！
在你的开源仓库中，我不是很明白 Waveform_header/ED047TC2.h 这个文件是怎么起作用的？如果我要自己适配其他屏幕，应该如何编写这个文件呢？
另：请问你有没有驱动这个屏幕的时序图？我有一个非元太的屏幕但我不确定能否与元太的引脚定义相契合。
我将在此上传关于他的数据手册，如果有时间还请你略加指教。
谢谢！
[datasheet.pdf](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/files/7950643/datasheet.pdf)

**Comment by liangyingy** [comment]
目前 Waveform_header/ED047TC2.h 这个文件并没有使用！

你可以调整这部分的时序，看看在你的屏幕上是否能起作用

[LilyGo-EPD47/src/epd_driver.c](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/tree/master/src/epd_driver.c)

![image](https://user-images.githubusercontent.com/46518962/153106163-f56e6560-4bdf-4f57-91f9-466317f4f896.png)
