### ISSUE TITLE
3D-printed STL case issues

### ISSUE THREAD

**Issue by scumola** [Xinyuan-LilyGO/LilyGo-EPD47#69]
I 3D printed the case that was provided with my resin printer and the 5 physical buttons were bent while putting the EPS47 into the case.  The plastic 'button' part of the buttons was bent upwards and now only click if they're bent back down - I'll probably have to order a whole new display because of this (discount for beta-testing?).  The case needs to be redesigned.  So-far the changes that are needed are:

* Buttons break (plastic 'button' part gets bent and needs to be replaced) when snapped into case
* USB-C connector hole is too high (needs to be closer to 'ground')
* 18650 battery hole is too narrow in both dimensions.  When a battery is inserted into the clips, the clips expand.  Even without a batter in the device, the hole was much too small though.

I've made alterations to the battery hole and the USB-C hole in my own design, but the switches are definitely a problem and mine now have to be replaced.

**Comment by G6EJD** [comment]
So you made a design error in the 3D case!
the battery connections are fin if using a standard 18650 cell - i.e. not with inbuilt protection.
The switches are standard pcb types, they are not for industrial/heavy use.

**Comment by scumola** [comment]
Perhaps pictures will help.  Note all other dimensions are pretty on-point, so I know that it's not a resolution or accuracy thing with my printer.  Again, I'm using a 2k resin printer, so resolution is pretty good.

![image](https://user-images.githubusercontent.com/386016/155996725-d535b22f-aa57-411d-8015-d2dbfff97d0e.png)
![image](https://user-images.githubusercontent.com/386016/155996897-64c8553d-8fb1-46e9-99d8-5df2209c256b.png)
![image](https://user-images.githubusercontent.com/386016/155997293-d8302ee9-abc6-4bb1-bec0-2a44cb4ceeba.png)

I can post my version of the case STL if/when I've perfected it and anyone is interested.

**Comment by G6EJD** [comment]
To be honest, I think your still learning how to design cases and it’s not about accuracy or resolution it’s about thinking through the board insertion/extraction process and usage and allowing tolerances for components because you can measure all those from the bare board.

**Comment by scumola** [comment]
To be honest, I think that you've never actually wedged the board into your case.  The switches break!  The battery clips don't fit!  You can't design a case for a board just by measuring it alone.  You have to actually test your design.  I've tested the original design and to be honest, it's crap and damages the board.  The resolution/accuracy comments were regarding the 3D printing process, not the design.
