### ISSUE TITLE
Lightresistenc

### ISSUE THREAD

**Issue by Oganisyan** [Xinyuan-LilyGO/LilyGo-EPD47#72]
In my project I use it outside.
On sunny days, the display lost its contrast.
Is it possible to counteract this on the software/hardware side?

**Comment by G6EJD** [comment]
No, this problem occurs with all E-paper displays, they need to be kept out of direct sunlight.

**Comment by G6EJD** [comment]
Are you going to close this issue as the problem was caused by incorrect use of the panel…

**Comment by Oganisyan** [comment]
I've seen that it doesn't work in direct sunlight:) 
My question was which frequency exactly disturbs it.
(Infrared, Ultraviolet or simply the temperature).
With a UV-IR filter it is probably possible to expand the range of use.
