### ISSUE TITLE
Is it possible to handle long press on reset button

### ISSUE THREAD

**Issue by BatsIhor** [Xinyuan-LilyGO/LilyGo-EPD47#73]
Hi, 
I'm working on device that suppose to have only one button. 
For now I'm using reset to restart device and load latest info from internet, but sometimes users want to reset device to factory settings and I wonder if I can somehow handle long press on reset button so when it restarts it actually does factory settings reset. 

Thank you

**Comment by G6EJD** [comment]
The Reset button is the device reset so it’s not possible, why not implement a combination of buttons or use one of the others if held for say 30-secs or whatever
