### ISSUE TITLE
Cannot Upload with Arduino IDE "A fatal error occurred: Failed to write to target RAM (result was 01070000)"

### ISSUE THREAD

**Issue by webfraggle** [Xinyuan-LilyGO/LilyGo-EPD47#78]
I cannot upload any example file via the arduino IDE. I got the error "A fatal error occurred: Failed to write to target RAM (result was 01070000)"

My settings are:
![image](https://user-images.githubusercontent.com/1697869/175826284-3e663122-10ea-461f-9f56-65ebbbd3f591.png)

The error looks like this:
![image](https://user-images.githubusercontent.com/1697869/175826342-ea3db010-2a02-4291-a8b1-a66ed6f9304c.png)

Can someone help me?

Thank you very much.

**Comment by G6EJD** [comment]
Which device are you writing to? Does it actually have PSRAM fitted?

**Comment by webfraggle** [comment]
@G6EJD It is a lilygo EPD47 and yes this should have PSRAM onboard

**Comment by webfraggle** [comment]
It seems to be a mac problem. I have a m1 mac with Monterey 12.4, the latest serial drivers worked in the past with some other esp32 boards. I hope my old boards will work in future.

I reactivated my windows machine and i was able to upload a bare minimum sketch. So I have to develop on my windows machine for this device.

**Comment by tavdog** [comment]
You most likely need the wch serial driver.  Since the chip shortage the CP21xx chips are being replaced with the another version which.  You need another serial driver.  It seems sketchy but it is legit, even Adafruit has had to use them https://learn.adafruit.com/how-to-install-drivers-for-wch-usb-to-serial-chips

**Comment by capnahab** [comment]
Tavdog suggestion worked a treatment for me with the same error on a mac (monterey 12.5). Good to see you here David.

**Comment by tavdog** [comment]
> It seems to be a mac problem. I have a m1 mac with Monterey 12.4, the latest serial drivers worked in the past with some other esp32 boards. I hope my old boards will work in future.
> 
> I reactivated my windows machine and i was able to upload a bare minimum sketch. So I have to develop on my windows machine for this device.

Did you try the wch driver ? I guarntee it will work.  Time to close this issue ?

**Comment by aaronpk** [comment]
I'm getting a similar error to this:

```
A fatal error occurred: Failed to write to target RAM (result was 01070000: Operation timed out)
```

I'm also using an M1 MacBook Air on Monterey 12.5.1, and I did install the new WCH driver and rebooted the system first.

**Comment by G6EJD** [comment]
Wrong board type selected.

**Comment by tavdog** [comment]
> I'm getting a similar error to this:
> 
> ```
> A fatal error occurred: Failed to write to target RAM (result was 01070000: Operation timed out)
> ```
> 
> I'm also using an M1 MacBook Air on Monterey 12.5.1, and I did install the new WCH driver and rebooted the system first.

did you try installing the wch serial drivers ?
