### ISSUE TITLE
Tutorial on Fonts and Images

### ISSUE THREAD

**Issue by kd8bxp** [Xinyuan-LilyGO/LilyGo-EPD47#8]
I've tried to create a custom font, with no luck. I've used the fontconvert.py tool and continue to get and error "valueError: code point 166 not found in font stack!".
I've tried to convert a ttf, and a otf. With no luck.
Is there a tutorial somewhere on how to create a font for the T5 4.7" 

a tutorial on creating a custom image would also be helpful, thank you.

**Comment by kd8bxp** [comment]
Update: I was able to get an image to convert and work, but still having issues with custom fonts. 
thanks

**Comment by lewisxhe** [comment]
Prerequisite you need to install python3 and install `freetype-py` using pip
The approximate process is like this:

```
sudo apt install python3-pip
python3 -m pip install freetype-py
``
The previous is the prerequisite for implementation, and then you need to store the font file you want to convert in the same path as fontconvert.py. This is just for more convenient operation. You can also fill in the font path.

Then just follow the command below to convert the font.
```
python3 fontconvert.py --compress demo 16 msyh.ttc> font.h
```

Explanation of specific parameters:

```
python3 fontconvert.py --compress [generated font name] [font size] [font file path]> [generated font file]
```

Of course, this only demonstrates the generation of standard ascii codes. If you need other fonts, you only need to fill in the unicode encoding of the font to be generated in the `fontconvert.py`  `intervals` list.

![demo](https://user-images.githubusercontent.com/22990954/104092951-446c1880-52c2-11eb-852e-8c50626eb340.png)

**Comment by lewisxhe** [comment]
By the way, please make sure that the unicode encoding in the `fontconvert.py` `intervals` list is included in your font file, otherwise please comment other encodings and only keep the 32,126 range!

![demo1](https://user-images.githubusercontent.com/22990954/104093029-d411c700-52c2-11eb-90ae-0c80df713f70.png)

**Comment by kd8bxp** [comment]
Thank you, 
Changing the intervals is what the problem was.
This is good information for anyone else who.

**Comment by kd8bxp** [comment]
Saw this information was added to a README in the scripts directory, I will close this issue. It's good information. Thanks
