### ISSUE TITLE
[Question] Partial Update

### ISSUE THREAD

**Issue by Kolesar** [Xinyuan-LilyGO/LilyGo-EPD47#81]
Does anyone know how to make a simple counter (up to 10, for example) with the partial update?

Of course, it is not necessary to have a counter, but from my point of view, it is the best example.

**Comment by sticilface** [comment]
I've been trying to do this.  And have not got it to work.  
You cannot use any of the drawing tools, rectangle, circle, text etc as they are hardcoded to the `EPD_WIDTH` and 'EPD_HEIGHT' parameters.  

You can write a smaller framebuffer using the send_image function... but you cannot write text or draw to it so it is fairly useless unless you have remade an image.  you cannot send a section of a framebuffer either... ie just the region you are interested in.  

This was my issue #80 ...
