### ISSUE TITLE
error: 'esp_lcd_panel_io.h' No such file

### ISSUE THREAD

**Issue by mackman12341** [Xinyuan-LilyGO/LilyGo-EPD47#86]
uploading the example sketches to the Lilygo board via Arduino IDE results in this error:

"Documents\Arduino\libraries\LilyGo-EPD47-master\src\i2s_data_bus.c:14:30: fatal error: esp_lcd_panel_io.h: No such file or directory"

I also cannot find this library in the various folders. Thanks!

**Comment by liangyingy** [comment]
#85
