### ISSUE TITLE
Problem loading weather project to t5-4.7 S3 board

### ISSUE THREAD

**Issue by Jxid** [Xinyuan-LilyGO/LilyGo-EPD47#89]
Hi i have problem loading weather project to t5-4.7 S3 board.
I starts uploading and at 80% of uploading i get a disconnect error and upload fails.
I have tried to upload demo sketch and it worked fine.
I am using Arduino IDE 2.0.3

**Comment by G6EJD** [comment]
It will not work.

**Comment by Jxid** [comment]
Why?

**Comment by G6EJD** [comment]
Piracy of code

**Comment by Jxid** [comment]
OK Thank you. Is there any other project for testing my board?

**Comment by lbuque** [comment]
Did you upload this [code](https://github.com/Xinyuan-LilyGO/LilyGo-EPD-4-7-OWM-Weather-Display/tree/web)?

**Comment by G6EJD** [comment]
No, that’s the issue, it’s a blatant copy of my code.

**Comment by lbuque** [comment]
Yes, this code is from https://github.com/markbirss/LilyGo-EPD-4-7-OWM-Weather-Display.

I learned from the leader that this code has been allowed by the developer for us to use. If you take issue with this copy, we may delete this copy.

**Comment by G6EJD** [comment]
I am the developer and I didn’t allow it. In that link the individual removed substantial parts of my licence and assumed that was ok, which is not.
Please remove my code.
