### ISSUE TITLE
Read a SD card using buttons in Lilygo T5 4.7 S3

### ISSUE THREAD

**Issue by FrancescSobrevela** [Xinyuan-LilyGO/LilyGo-EPD47#90]
Hello.
We are working on a project where we need to read a SD card using the 3 buttons we have on the Lilygo T5 4.7 S3. It`s possible to help us with a code in which we can read that SD card?

**Comment by lbuque** [comment]
@FrancescSobrevela [Here](https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/master/examples/demo/demo.ino#L38-L51) is about the use of sd card, is it helpful to you?
