### ISSUE TITLE
Function of the trimmer (potentiometer)?

### ISSUE THREAD

**Issue by dreamy1** [Xinyuan-LilyGO/LilyGo-EPD47#92]
Hello,

just wondering about the trimmer/potentiometer on the back of the pcb. What function has this part? I can't find it in the schematic.

Thanks,
Stefan

**Comment by valahna** [comment]
Hi Stefan,

I found your potentiometer in the schematic, in Block A1 - I believe it to be a means to control the input offset voltage of the op-amp (LM358DR2G ) - at least that is my best guess :)

-Val

**Comment by dreamy1** [comment]
Thanks Val,

yes, i found it. It is for adjusting the -15V supply voltage for the e-paper. 

Regards,
Stefan
