### ISSUE TITLE
EPD SPI Example: Please add some epd_print text out examples

### ISSUE THREAD

**Issue by markbirss** [Xinyuan-LilyGO/LilyGo-EPD47#94]
Currently only able to show jpeg images, how about ability to output text ?
https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/master/examples/spi_driver/test/epd.py

**Comment by markbirss** [comment]
> String text = “Hello world”; char * data = const_cast<char*>(text.c_str()); int x = 10; Int y = 10; write_string(&currentFont, data, &x, &y, framebuffer);

Im looking for python example for the slave spi driver?

**Comment by roearturo** [comment]
> There’s already an example function: def draw_char(

An example of how to use the function would be great, I can’t figure out how to use it
